move ltsmin tests to tests/ltsmin/
* spot/ltsmin/defs.in: Delete.
* spot/ltsmin/README, spot/ltsmin/beem-peterson.4.dve,
spot/ltsmin/check.test, spot/ltsmin/elevator2.1.pm,
spot/ltsmin/finite.dve, spot/ltsmin/finite.pm, spot/ltsmin/finite.test,
spot/ltsmin/finite2.test, spot/ltsmin/kripke.test,
spot/ltsmin/modelcheck.cc: Move...
* tests/ltsmin/: ... here.
* spot/ltsmin/README: Point to tests/ltsmin/README.
* README, configure.ac, spot/ltsmin/Makefile.am, tests/.gitignore,
tests/Makefile.am, tests/core/defs.in: Adjust.

diff --git a/tests/core/defs.in b/tests/core/defs.in
--- a/tests/core/defs.in
+++ b/tests/core/defs.in
@@ -33,9 +33,9 @@ if test -z "$srcdir"; then
    test $srcdir = $0 && srcdir=.
 fi
 
-# Ensure $srcdir is set correctly.
-test -f $srcdir/defs.in || {
-   echo "$srcdir/defs.in not found, check \$srcdir" 1>&2
+# Ensure $srcdir is set correctly.  It should point to a subdirectory of tests.
+test -f $srcdir/../core/defs.in || {
+   echo "$srcdir/../core/defs.in not found, check \$srcdir" 1>&2
    exit 1
 }
 
@@ -66,7 +66,7 @@ LTL2BA='@LTL2BA@'
 PYTHON='@PYTHON@'
 top_srcdir='@abs_top_srcdir@'
 
-# The test cases assume these variable are undefined
+# The test cases assume these variables are undefined
 unset SPOT_DOTEXTRA
 unset SPOT_DOTDEFAULT
 
